[tool.poetry]
name = "plana"
version = "0.1.0"
description = "A twitter bot"
authors = ["sauhardh <sauhardhakafle12@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
feedparser = "^6.0.11"
dotenv = "^0.9.9"
groq = "^0.31.0"
beautifulsoup4 = "^4.13.4"
trafilatura = "^2.0.0"
requests = "^2.32.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
