NUMBER_OF_NEWS: int = 5
VIRAL_TOKENS: set = {
    "trump",
    "shooting",
    "drugs",
    "gun",
    "illigal",
    "elon musk",
    "celebrity",
    "rapper",
    "war",
    "vulgar",
    "politics",
    "AI",
    "youtuber",
    "putin",
    "zelensky",
    "ukrane",
    "russia",
    "controversy",
    "Mr beast",
    "Modi",
    "prime minister",
    "president",
    "India",
    "disaster",
    "accident",
    "invention",
    "crash",
    "Trump",
    "elon",
}

AI_CONTENT: str = f"You are assistant of social media content creator. You have to select the news that has actual content, depth, should not be booring, potential to go viral and rephrase it on your own words. Do not select opinion, essay, writing. By the ranking of your own, virality should be greater than 7 out of 10. Currently viral topics include {VIRAL_TOKENS}"
MODEL: str = "llama-3.3-70b-versatile"
