name: Post Tweet

on:
  workflow_dispatch:
    # schedule:
    #     - cron: "0 6-23/4 * * *" # 6 AM -- 10 PM every 4hr

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            with:
              fetch-depth: 0 # for rebase

          - name: Set up python
            uses: actions/setup-python@v5
            with:
                python-version: "3.12"

          - name: Sync latest main
            run: |
              git config --local user.email "sauhardhakafle0@gmail.com"
              git config --local user.name "SauhardhaKafle"
              git pull --rebase origin main || true
    

          - name: Install poetry
            run: pip install poetry
          - name: Install dependencies
            run: poetry install --no-interaction --no-root

          - name: Run bot
            env:
                X_API_KEY: ${{ secrets.X_API_KEY }}
                X_API_KEY_SECRET: ${{ secrets.X_API_KEY_SECRET }}
                X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
                X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }} 
                GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}     
            run: poetry run python -m bot
          
          - name: Commit and Push Changes
            run: |
               git add .
               git commit -m "Updated time.txt" || echo "No changes to commit"
               git pull --rebase origin main || true
               git push origin main
        



